version: "3.8"

services:
  websocket-suntech:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-suntech
    restart: unless-stopped

    ports:
      - "3001:3001"
      - "5000:5000"

    environment:
      - HOST=0.0.0.0
      - TCP_PORT=5000
      - WS_PORT=3001

    # Health check
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
